# ruff: noqa: N802, ARG002, I001, F401, E501
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from daena.api.pb2 import daena_pb2 as daena_dot_v1_dot_daena__pb2

GRPC_GENERATED_VERSION = "1.82.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in daena/v1/daena_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DaenaStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
            "/daena.v1.Daena/GetStatus",
            request_serializer=daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.StatusResponse.FromString,
            _registered_method=True,
        )
        self.GetHealth = channel.unary_unary(
            "/daena.v1.Daena/GetHealth",
            request_serializer=daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.GetConfig = channel.unary_unary(
            "/daena.v1.Daena/GetConfig",
            request_serializer=daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.ConfigResponse.FromString,
            _registered_method=True,
        )
        self.ListPlugins = channel.unary_unary(
            "/daena.v1.Daena/ListPlugins",
            request_serializer=daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.PluginListResponse.FromString,
            _registered_method=True,
        )
        self.GetQueueState = channel.unary_unary(
            "/daena.v1.Daena/GetQueueState",
            request_serializer=daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.QueueStateResponse.FromString,
            _registered_method=True,
        )
        self.ListPendingRecords = channel.unary_unary(
            "/daena.v1.Daena/ListPendingRecords",
            request_serializer=daena_dot_v1_dot_daena__pb2.Pagination.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.RecordList.FromString,
            _registered_method=True,
        )
        self.ListDeadRecords = channel.unary_unary(
            "/daena.v1.Daena/ListDeadRecords",
            request_serializer=daena_dot_v1_dot_daena__pb2.Pagination.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.RecordList.FromString,
            _registered_method=True,
        )
        self.ListSinks = channel.unary_unary(
            "/daena.v1.Daena/ListSinks",
            request_serializer=daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.SinkList.FromString,
            _registered_method=True,
        )
        self.ReloadConfig = channel.unary_unary(
            "/daena.v1.Daena/ReloadConfig",
            request_serializer=daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            response_deserializer=daena_dot_v1_dot_daena__pb2.ReloadResponse.FromString,
            _registered_method=True,
        )


class DaenaServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPlugins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQueueState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListPendingRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListDeadRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSinks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReloadConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DaenaServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Empty.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.StatusResponse.SerializeToString,
        ),
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Empty.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.HealthResponse.SerializeToString,
        ),
        "GetConfig": grpc.unary_unary_rpc_method_handler(
            servicer.GetConfig,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Empty.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.ConfigResponse.SerializeToString,
        ),
        "ListPlugins": grpc.unary_unary_rpc_method_handler(
            servicer.ListPlugins,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Empty.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.PluginListResponse.SerializeToString,
        ),
        "GetQueueState": grpc.unary_unary_rpc_method_handler(
            servicer.GetQueueState,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Empty.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.QueueStateResponse.SerializeToString,
        ),
        "ListPendingRecords": grpc.unary_unary_rpc_method_handler(
            servicer.ListPendingRecords,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Pagination.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.RecordList.SerializeToString,
        ),
        "ListDeadRecords": grpc.unary_unary_rpc_method_handler(
            servicer.ListDeadRecords,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Pagination.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.RecordList.SerializeToString,
        ),
        "ListSinks": grpc.unary_unary_rpc_method_handler(
            servicer.ListSinks,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Empty.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.SinkList.SerializeToString,
        ),
        "ReloadConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ReloadConfig,
            request_deserializer=daena_dot_v1_dot_daena__pb2.Empty.FromString,
            response_serializer=daena_dot_v1_dot_daena__pb2.ReloadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("daena.v1.Daena", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("daena.v1.Daena", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Daena:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/GetStatus",
            daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            daena_dot_v1_dot_daena__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/GetHealth",
            daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            daena_dot_v1_dot_daena__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/GetConfig",
            daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            daena_dot_v1_dot_daena__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPlugins(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/ListPlugins",
            daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            daena_dot_v1_dot_daena__pb2.PluginListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetQueueState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/GetQueueState",
            daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            daena_dot_v1_dot_daena__pb2.QueueStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListPendingRecords(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/ListPendingRecords",
            daena_dot_v1_dot_daena__pb2.Pagination.SerializeToString,
            daena_dot_v1_dot_daena__pb2.RecordList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListDeadRecords(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/ListDeadRecords",
            daena_dot_v1_dot_daena__pb2.Pagination.SerializeToString,
            daena_dot_v1_dot_daena__pb2.RecordList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListSinks(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/ListSinks",
            daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            daena_dot_v1_dot_daena__pb2.SinkList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReloadConfig(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/daena.v1.Daena/ReloadConfig",
            daena_dot_v1_dot_daena__pb2.Empty.SerializeToString,
            daena_dot_v1_dot_daena__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
